module.exports = {
  pageName: '',
  browser: {},
  page: {},
  page2: {},
  base_URL: 'https://www.instagram.com',
  login_URL: 'https://www.instagram.com/accounts/login/',
  TAG_URL: (tag) => `https://www.instagram.com/explore/tags/${tag}/`,
  Page_URL: (name) => `https://www.instagram.com/${name}`,
  used_pages: [],
  usedTargets: [],
  whiteList: [],
  comments: [],
  directTexts: [],
  posts: 0,
  following: 0,
  followers: 0,
  followCounter: { hasDone: 0, round: 0 },
  // unfollowCounter: { hasDone: 0, round: 0 },
  likeCounter: { hasDone: 0, round: 0 },
  Unfollowed: 0,
  hasCommented: 0,
  hasSentDirect: 0,
  followLimit: 10,
  unfollowLimit: 20,
  likeLimit: 20,
  followPrivateLimit: 9,
  directToSendPerProcess: 1,
  unfollowStartAfter: 1500,
  commentPace: 6,
  processPace: 'slow',
  commentQue: 0,
  directQue: 0,
  writeComment: true,
  notFollowBusinessPage: false, // If it should follow the buisness pages
  followPrivate: false, // If it should follow the private pages
  likeLastPost: true,
  childs: {}, // do not delete it. child process use this
  turn: 'getDetail',
  test: 'hello',
  sixHours: 0,
  quarterCounter: 0,
};
